version: '3.9'
name: shop-app-db

services:
  db:
    image: postgres:16-alpine
    restart: always
    container_name: shop-app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop-app-db
    ports:
      - "5439:5432"
    volumes:
      - shop_db_data:/var/lib/postgresql/data

volumes:
  shop_db_data:
    driver: local