version: '3.9'
name: shop-app-db

services:
  db:
    image: postgres:16-alpine
    restart: always
    container_name: shop-app-db
    environment:
      POSTGRES_USER: shop_admin
      POSTGRES_PASSWORD: MySuperSecurePassword123!
      POSTGRES_DB: shop_app_db
    ports:
      - "127.0.0.1:5439:5432"
    volumes:
      - shop_db_data:/var/lib/postgresql/data

volumes:
  shop_db_data:
    driver: local